config/routes.rb
require 'api_constraints'

ZfsstatsRails::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :devices
      resources :job_reports
      resources :jobs
      resources :measurements
      resources :servers
      resources :users
    end
  end

  resources :dashboard
  resources :devices
  resources :job_reports
  resources :measurements
  resources :servers do
    resources :jobs
  end
  resources :sessions
  resources :users

  root to: 'dashboard#index'

  

  

end

app/models/job_report.rb
class JobReport
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content, type: String
  field :status, type: Integer, :default => 0
  
  belongs_to :job, dependent: :destroy
end

app/controllers/api/v1/job_reports_controller.rb
module Api
  module V1
    class JobReportsController < ApiController
      respond_to :json
      # GET /job_reports
      # GET /job_reports.xml
      def index
      	@job_reports = JobReport.all
        @job_reports = @job_reports.where(:created_at.gt => params[:start]) if params.has_key?(:start)
        @job_reports = @job_reports.where(:created_at.lt => params[:end]) if params.has_key?(:end)
        @job_reports = @job_reports.where(:job_id => params[:job_id]) if params.has_key?(:job_id)
        @job_reports = @job_reports.where(:status.gte => params[:status]) if params.has_key?(:status)
        @job_reports = @job_reports.limit(params[:limit]) if params.has_key?(:limit)
        respond_with(@job_reports)
      end

      # GET /job_reports/1
      # GET /job_reports/1.xml
      def show
        @job_report = JobReport.find(params[:id])
        respond_with(@job_report)
      end

      # GET /job_reports/new
      # GET /job_reports/new.xml
      def new
        @job_report = JobReport.new
        respond_with(@job_report)
      end

      # GET /job_reports/1/edit
      def edit
        @job_report = JobReport.find(params[:id])
      end

      # POST /job_reports
      # POST /job_reports.xml
      def create
        @job_report = JobReport.new(params[:job_report])
        @job_report.save
        respond_with(@job_report)
      end

      # PUT /job_reports/1
      # PUT /job_reports/1.xml
      def update
        @job_report = JobReport.find(params[:id])
        flash[:notice] = 'JobReport was successfully updated.' if @job_report.update_attributes(params[:job_report])
        respond_with(@job_report)
      end

      # DELETE /job_reports/1
      # DELETE /job_reports/1.xml
      def destroy
        @job_report = JobReport.find(params[:id])
        @job_report.destroy
        respond_with(@job_report)
      end
    end
  end
end

app/controllers/job_reports_controller.rb
class JobReportsController < ApplicationController
  respond_to :json
  # GET /job_reports
  # GET /job_reports.xml
  def index
    @job_reports = JobReport.all
    respond_with(@job_reports)
  end

  # GET /job_reports/1
  # GET /job_reports/1.xml
  def show
    @job_report = JobReport.find(params[:id])
    respond_with(@job_report)
  end

  # GET /job_reports/new
  # GET /job_reports/new.xml
  def new
    @job_report = JobReport.new
    respond_with(@job_report)
  end

  # GET /job_reports/1/edit
  def edit
    @job_report = JobReport.find(params[:id])
  end

  # POST /job_reports
  # POST /job_reports.xml
  def create
    @job_report = JobReport.new(params[:job_report])
    flash[:notice] = 'JobReport was successfully created.' if @job_report.save
    respond_with(@job_report)
  end

  # PUT /job_reports/1
  # PUT /job_reports/1.xml
  def update
    @job_report = JobReport.find(params[:id])
    flash[:notice] = 'JobReport was successfully updated.' if @job_report.update_attributes(params[:job_report])
    respond_with(@job_report)
  end

  # DELETE /job_reports/1
  # DELETE /job_reports/1.xml
  def destroy
    @job_report = JobReport.find(params[:id])
    @job_report.destroy
    respond_with(@job_report)
  end
end

app/helpers/job_reports_helper.rb
module JobReportsHelper
end

app/views/job_reports/_form.html.erb
<%= simple_form_for(@job_report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/job_reports/edit.html.erb
<h1>Editing job_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_report %> |
<%= link_to 'Back', job_reports_path %>

app/views/job_reports/index.html.erb
<h1>Listing job_reports</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @job_reports.each do |job_report| %>
      <tr>
        <td><%= job_report.content %></td>
        <td><%= link_to 'Show', job_report %></td>
        <td><%= link_to 'Edit', edit_job_report_path(job_report) %></td>
        <td><%= link_to 'Destroy', job_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job report', new_job_report_path %>

app/views/job_reports/new.html.erb
<h1>New job_report</h1>

<%= render 'form' %>

<%= link_to 'Back', job_reports_path %>

app/views/job_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @job_report.content %>
</p>

<%= link_to 'Edit', edit_job_report_path(@job_report) %> |
<%= link_to 'Back', job_reports_path %>