config/routes.rb
require 'api_constraints'

ZfsstatsRails::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :devices
      resources :job_reports
      resources :jobs
      resources :measurements
      resources :servers
      resources :users
    end
  end

  resources :dashboard
  resources :devices
  resources :job_reports
  resources :measurements
  resources :servers do
    resources :jobs
  end
  resources :sessions
  resources :users

  root to: 'dashboard#index'

  

  

end

app/models/server.rb
require 'ipaddr'
class Server
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessor :status

  before_create :generate_access_token

  field :_id, type: String, default: -> { name.to_s.parameterize }
  field :name, type: String
  field :fqdn, type: String
  field :IPv4Address, type: IPAddr
  field :IPv6Address, type: IPAddr
  field :apiKey, type: String
  field :description, type: String

  has_many :devices, dependent: :destroy
  has_many :jobs, dependent: :destroy

  belongs_to :user, :inverse_of => :servers, :class_name => 'User'

  validates_presence_of :name
  validate :name_not_changed

  def name=(name)
    write_attribute(:name, name)
    write_attribute(:_id, name)
  end

  def status
    status = 0
    self.devices.where(:type => 'zpool').all.each do |zpool|
      status += 1 if zpool.state != "ONLINE"
    end
    return status
  end

  private
    def generate_access_token
      self.apiKey = SecureRandom.hex
    end

    def name_not_changed
      if name_changed? && self.persisted?
        errors.add(:name, "Change of name is not allowed!")
      end
    end
end

app/controllers/api/v1/servers_controller.rb
module Api
  module V1
    class ServersController < ApiController
      before_action :set_server, only: [:show, :edit, :update, :destroy]
      respond_to :json

      # GET /servers
      # GET /servers.xml
      def index
        @servers = Server.all
        @servers = @servers.limit(params[:limit]) if params.has_key?(:limit)
        if params.has_key?(:order_by) && params.has_key?(:order)
          if Server.fields.keys.include?(params[:order_by]) || ['status'].include?(params[:order_by])
            @servers = @servers.sort_by!{ |s| s.send(params[:order_by])}
            @servers = @servers.reverse if params[:order] == 'desc'
          end
        end
        respond_with(@servers)
      end

      # GET /servers/1
      # GET /servers/1.xml
      def show
        @server = Server.find(params[:id])
        respond_with(@server)
      end

      # GET /servers/newd
      # GET /servers/new.xml
      def new
        @server = Server.new
        respond_with(@server)
      end

      # GET /servers/1/edit
      def edit
        @server = Server.find(params[:id])
      end

      # POST /servers
      # POST /servers.xml
      def create
        @server = Server.new(params[:server])
        respond_with(@server)
      end

      # PUT /servers/1
      # PUT /servers/1.xml
      def update
        @server = Server.find(params[:id])
        @server.update_attributes(params[:server])
        respond_with(@server)
      end

      # DELETE /servers/1
      # DELETE /servers/1.xml
      def destroy
        @server = Server.find(params[:id])
        @server.destroy
        respond_with(@server)
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_server
          @server = Server.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def server_params
          params.require(:server).permit(:name, :fqdn, :IPv4Address, :IPv6Address, :description)
        end
    end
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]
  respond_to :html
  load_and_authorize_resource

  # GET /servers
  # GET /servers.xml
  def index
    @servers = Server.all
    respond_with(@servers)
  end

  # GET /servers/1
  # GET /servers/1.xml
  def show
    @server = Server.find(params[:id])
    respond_with(@server)
  end

  # GET /servers/new
  # GET /servers/new.xml
  def new
    @server = Server.new
    respond_with(@server)
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.xml
  def create
    @server = Server.new(params[:server])
    flash[:notice] = 'Server was successfully created.' if @server.save
    respond_with(@server)
  end

  # PUT /servers/1
  # PUT /servers/1.xml
  def update
    @server = Server.find(params[:id])
    flash[:notice] = 'Server was successfully updated.' if @server.update_attributes(params[:server])
    respond_with(@server)
  end

  # DELETE /servers/1
  # DELETE /servers/1.xml
  def destroy
    @server = Server.find(params[:id])
    @server.destroy
    respond_with(@server)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:server).permit(:name, :fqdn, :IPv4Address, :IPv6Address, :description, :user)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server, :html => { :class => 'form-horizontal' }) do |f| %>
  <h2><%= controller.action_name.capitalize %> Server</h2>

  <div class="col-md-5">
    <legend>Server information</legend>
    <div class="form-group">
      <%= f.label :name, 'Hostname', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :name, placeholder: "Hostname", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :fqdn, 'FQDN', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :fqdn, placeholder: "Fully Qualified Domain Name", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv4Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv4Address, placeholder: "IPv4 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv6Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv6Address, placeholder: "IPv6 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_area :description, placeholder: "Description", class: "form-control" %></div>
    </div>

    <%= f.hidden_field :user, { value: current_user.id } %>
  </div>

  <div class="col-md-12">
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>
</div>

app/views/servers/edit.html.erb
<%= form_for(@server, :html => { :class => 'form-horizontal' }) do |f| %>
  <h2><%= controller.action_name.capitalize %> Server</h2>

  <div class="col-md-5">
    <legend>Server information</legend>
    <div class="form-group">
      <%= f.label :name, 'Hostname', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :name, placeholder: "Hostname", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :fqdn, 'FQDN', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :fqdn, placeholder: "Fully Qualified Domain Name", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv4Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv4Address, placeholder: "IPv4 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv6Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv6Address, placeholder: "IPv6 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_area :description, placeholder: "Description", class: "form-control" %></div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>
</div>

app/views/servers/index.html.erb
<legend><%= controller.action_name.capitalize %> Servers</legend>
<p>
  On this page are all your ZFS server listed in a nice bootstrapp'd table.
</p>
<table class="table table-striped" style="font-size:12px;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Full Qualified Domain Name (FQDN)</th>
      <th>IPv4 Address</th>
      <th>Nr. of devices</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.fqdn %></td>
        <td><%= server.IPv4Address %></td>
        <td><%= server.devices.size %></td>
        <td>
          <% if can? :read, server %>
            <%= link_to image_tag('/img/info.png', :size => '16x16'), server%>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <% if can? :update, server %>
            <%= link_to image_tag('/img/edit.png', :size => '16x16'), edit_server_path(server)%>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <% if can? :delete, server %>
            <%= link_to image_tag('/img/delete.png', :size => '16x16'), server, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            -
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Server %>
  <%= link_to 'New Server', new_server_path, :class => 'btn btn-primary' %>
<% end %>

app/views/servers/new.html.erb
<%= form_for(@server, :html => { :class => 'form-horizontal' }) do |f| %>
  <h2><%= controller.action_name.capitalize %> Server</h2>

  <div class="col-md-5">
    <legend>Server information</legend>
    <div class="form-group">
      <%= f.label :name, 'Hostname', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :name, placeholder: "Hostname", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :fqdn, 'FQDN', class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :fqdn, placeholder: "Fully Qualified Domain Name", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv4Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv4Address, placeholder: "IPv4 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :IPv6Address, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_field :IPv6Address, placeholder: "IPv6 Address", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.text_area :description, placeholder: "Description", class: "form-control" %></div>
    </div>

    <%= f.hidden_field :user, { value: current_user.id } %>
  </div>

  <div class="col-md-12">
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>
</div>

app/views/servers/show.html.erb
<div ng-view>
</div>