config/routes.rb
require 'api_constraints'

ZfsstatsRails::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :devices
      resources :job_reports
      resources :jobs
      resources :measurements
      resources :servers
      resources :users
    end
  end

  resources :dashboard
  resources :devices
  resources :job_reports
  resources :measurements
  resources :servers do
    resources :jobs
  end
  resources :sessions
  resources :users

  root to: 'dashboard#index'

  

  

end

app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::MassAssignmentSecurity
  include BCrypt

  ROLES = %w[admin default]

  field :firstname, type: String
  field :lastname, type: String
  field :email, type: String
  field :password_hash, type: String
  field :role, type: String, default: 'default'
  field :lastLogin, type: DateTime

  field :measurementInterval, type: Integer, default: 60

  has_many :servers, :inverse_of => :user, :class_name => 'Server'

  attr_accessor :password, :password_confirmation
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_inclusion_of :role, in: ['default', 'admin']

  def update(params)
    puts params
    if(params[:password].nil? && params[:password_confirmation].nil?)
      raise "error"
      params.delete :password
      params.delete :password_confirmation
    end
    super(params)
  end
  
  def self.find_by_email(email)
  	where(:email => email).first
	end
  
  def self.authenticate(user_email, password)
    user = find_by_email user_email
    return if user.nil?
    user_pass = Password.new(user.password_hash)
    if user_pass == password
      user.lastLogin = DateTime.current()
      user.save()
    	return user
    else
    	return false
    end
  end

  def admin
    return true if self.role == 'admin'
    return false
  end
  
  protected
  
  def encrypt_password
    if password.present?
      self.password_hash = Password.create(@password)
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      before_action :set_user, only: [:show, :edit, :update, :destroy]
      respond_to :json

      # GET /users
      # GET /users.json
      def index
        @users = User.all
        respond_with @users
      end

      # GET /users/1
      # GET /users/1.json
      def show
        respond_with @user
      end

      # POST /users
      # POST /users.json
      def create
        @user = User.new(user_params)
        @user.save
        return @user
      end

      # PATCH/PUT /users/1
      # PATCH/PUT /users/1.json
      def update
        @user.update(user_params)
        respond_with @user
      end

      # DELETE /users/1
      # DELETE /users/1.json
      def destroy
        @user.destroy
        respond_with @user
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_user
          @user = User.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def user_params
          if current_user.admin
            params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :role)
          else
            params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
          end
        end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_with @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_with @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update(user_params)
    respond_with @user
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_with @user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      if current_user.admin
        params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :measurementInterval, :role)
      else
        params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :measurementInterval)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <h2><%= controller.action_name.capitalize %> User</h2>
  <div class="col-md-5">
    <legend>Personal information</legend>
    <div class="form-group">
        <%= f.label :firstname, class: "control-label col-md-3" %>
        <div class="col-md-9"><%= f.text_field :firstname, placeholder: "First name", class: "form-control" %></div>
    </div>

    <div class="form-group">
        <%= f.label :lastname, class: "control-label col-md-3" %>
        <div class="col-md-9"><%= f.text_field :lastname, placeholder: "Last name", class: "form-control" %></div>
    </div>

    <div class="form-group">
        <%= f.label :email, class: "control-label col-md-3" %>
        <div class="col-md-9"><%= f.text_field :email, placeholder: "E-Mail address", class: "form-control" %></div>
    </div>

    <% if current_user.admin %>
      <div class="form-group">
        <%= f.label :role, class: "control-label col-md-3" %>
        <div class="col-md-9"><%= f.select :role, User::ROLES, {}, {class: "form-control" } %></div>
      </div>
    <% end %>

    <div class="form-group">
        <%= f.label :password, class: "control-label col-md-3" %>
        <div class="col-md-9"><%= f.password_field :password, placeholder: "Password", class: "form-control" %></div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "control-label col-md-3" %>
      <div class="col-md-9"><%= f.password_field :password_confirmation, placeholder: "Password confirmation", class: "form-control" %></div>
    </div>
  </div>

  <div class="col-md-7">
    <legend>User preferences</legend>
    <div class="form-group">
      <%= f.label :measurementInterval, 'Measurement Interval in seconds', class: "control-label col-md-8" %>
      <div class="col-md-4"><%= f.number_field :measurementInterval, class: "form-control" %></div>
    </div>
  </div>
  
  <div class="col-md-12">
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<legend><%= controller.action_name.capitalize %> Users</legend>
<p>
  On this page are all users listed in a nice bootstrapp'd table.
</p>

<table class="table table-striped" style="font-size:12px;">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><b><%= user.role %></b></td>
        <td>
          <% if can? :read, user %>
            <%= link_to image_tag('/img/info.png', :size => '16x16'), user%>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <% if can? :update, user %>
            <%= link_to image_tag('/img/edit.png', :size => '16x16'), edit_user_path(user)%>
          <% else %>
            -
          <% end %>
        </td>
        <td>
          <% if can? :delete, user %>
            <%= link_to image_tag('/img/delete.png', :size => '16x16'), user, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            -
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, User %>
  <%= link_to 'New User', new_user_path, :class => 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="span8">
  <legend><%= controller.action_name.capitalize %> User</legend>
  <p id="notice"><%= notice %></p>
  <table class="table table-striped" style="font-size:12px;">
    <tr>
      <th>First name</th>
      <td><%= @user.firstname %></td>
    </tr>

    <tr>
      <th>Last name</th>
      <td><%= @user.lastname %></td>
    </tr>

    <tr>
      <th>E-mail</th>
      <td><%= @user.email %></td>
    </tr>

    <tr>
      <th>Created at</th>
      <td><%= @user.created_at %></td>
    </tr>

    <tr>
      <th>Last updated</th>
      <td><%= @user.updated_at %></td>
    </tr>

  </table>

  <div class="form-actions">
    <%= link_to 'Back', users_path, :class => 'btn btn-primary' %>
    <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-warning' %>
    <%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
  </div>
</div>